#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Joel Haasnoot
"""Write the Android launcher icon: the "unknown signal" signal head with its question-mark badge on
the app's orange, as adaptive-icon vector drawables (foreground, background, monochrome).

Usage: make_app_icon.py <android res dir>
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from make_unknown_signal_icons import HEAD, QUESTION_MARK  # noqa: E402

ORANGE = "#FFE8640A"
DARK = "#FF" + HEAD.lstrip("#").upper()
LAMP = "#FFA6A6A6"
WHITE = "#FFFFFFFF"
SCALE = 2.85  # keeps the signal inside the 66 dp safe zone of the 108 dp adaptive icon
CENTER = (9.52, 8.55)  # centre of the signal-with-badge drawing in its 18 x 17.12 units

HEADER = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by pipeline/make_app_icon.py -->\n'


def n(value):
    return f"{value:.3f}".rstrip("0").rstrip(".")


def rounded_bar(x, y, w, h):
    r = w / 2
    return (f"M{n(x + r)},{n(y)} A{n(r)},{n(r)} 0 0 1 {n(x + w)},{n(y + r)} L{n(x + w)},{n(y + h - r)} "
            f"A{n(r)},{n(r)} 0 0 1 {n(x)},{n(y + h - r)} L{n(x)},{n(y + r)} A{n(r)},{n(r)} 0 0 1 {n(x + r)},{n(y)} Z")


def circle(cx, cy, r):
    return f"M{n(cx - r)},{n(cy)} A{n(r)},{n(r)} 0 1 1 {n(cx + r)},{n(cy)} A{n(r)},{n(r)} 0 1 1 {n(cx - r)},{n(cy)} Z"


def vector(body):
    tx = 54 - CENTER[0] * SCALE
    ty = 54 - CENTER[1] * SCALE
    return (HEADER +
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="108dp" android:height="108dp"\n'
            '    android:viewportWidth="108" android:viewportHeight="108">\n'
            f'    <group android:translateX="{tx:.3f}" android:translateY="{ty:.3f}" '
            f'android:scaleX="{SCALE}" android:scaleY="{SCALE}">\n{body}    </group>\n</vector>\n')


HEAD_BAR = rounded_bar(1.6, 0.55, 7.8, 16)
LAMPS = [circle(5.5, 4.5, 2.15), circle(5.5, 12.4, 2.15)]
QUESTION = (
    '        <group android:translateX="12.9" android:translateY="11.95" '
    f'android:scaleX="{5.4 / 9.08:.4f}" android:scaleY="{5.4 / 9.08:.4f}">\n'
    '            <group android:translateX="-8.96" android:translateY="-9.55">\n'
    f'                <path android:fillColor="{DARK}" android:pathData="{QUESTION_MARK}"/>\n'
    '            </group>\n        </group>\n'
)

FOREGROUND = vector(
    f'        <path android:fillColor="{DARK}" android:pathData="{HEAD_BAR}"/>\n'
    + "".join(f'        <path android:fillColor="{LAMP}" android:pathData="{lamp}"/>\n' for lamp in LAMPS)
    + f'        <path android:fillColor="{WHITE}" android:strokeColor="{DARK}" android:strokeWidth="1.3" '
      f'android:pathData="{circle(12.9, 11.9, 4.55)}"/>\n'
    + QUESTION
)

# Themed icons are single-colour silhouettes: the signal head with its lamps cut out.
MONOCHROME = vector(
    f'        <path android:fillColor="{DARK}" android:fillType="evenOdd" '
    f'android:pathData="{HEAD_BAR} {" ".join(LAMPS)}"/>\n'
)

BACKGROUND = (HEADER +
              '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
              '    android:width="108dp" android:height="108dp"\n'
              '    android:viewportWidth="108" android:viewportHeight="108">\n'
              f'    <path android:fillColor="{ORANGE}" android:pathData="M0,0h108v108H0z"/>\n</vector>\n')

ADAPTIVE = (HEADER +
            '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@drawable/ic_launcher_background" />\n'
            '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
            '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
            '</adaptive-icon>\n')


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: make_app_icon.py <android res dir>")
    res = sys.argv[1]
    files = {
        "drawable/ic_launcher_foreground.xml": FOREGROUND,
        "drawable/ic_launcher_background.xml": BACKGROUND,
        "drawable/ic_launcher_monochrome.xml": MONOCHROME,
        "mipmap-anydpi-v26/ic_launcher.xml": ADAPTIVE,
    }
    for path, content in files.items():
        full = os.path.join(res, path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as f:
            f.write(content)
    print(f"wrote {len(files)} icon resources to {res}")


if __name__ == "__main__":
    main()
