#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Joel Haasnoot
"""Write the Android launcher icon: a two-lamp signal head showing green on the app's orange, as
adaptive-icon vector drawables (foreground, background, monochrome). The head matches the map's
signal icons from make_unknown_signal_icons.py.

Usage: make_app_icon.py <android res dir>
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from make_unknown_signal_icons import HEAD  # noqa: E402

ORANGE = "#FFE8640A"
DARK = "#FF" + HEAD.lstrip("#").upper()
UNLIT = "#FF5A5A5A"
GREEN = "#FF2EE06F"
GLOW = "#662EE06F"
SCALE = 3.3  # keeps the signal inside the 66 dp safe zone of the 108 dp adaptive icon
CENTER = (9.0, 8.55)  # centre of the signal head in its 18 x 17.12 units

HEADER = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by pipeline/make_app_icon.py -->\n'


def n(value):
    return f"{value:.3f}".rstrip("0").rstrip(".")


def rounded_bar(x, y, w, h):
    r = w / 2
    return (f"M{n(x + r)},{n(y)} A{n(r)},{n(r)} 0 0 1 {n(x + w)},{n(y + r)} L{n(x + w)},{n(y + h - r)} "
            f"A{n(r)},{n(r)} 0 0 1 {n(x)},{n(y + h - r)} L{n(x)},{n(y + r)} A{n(r)},{n(r)} 0 0 1 {n(x + r)},{n(y)} Z")


def circle(cx, cy, r):
    return f"M{n(cx - r)},{n(cy)} A{n(r)},{n(r)} 0 1 1 {n(cx + r)},{n(cy)} A{n(r)},{n(r)} 0 1 1 {n(cx - r)},{n(cy)} Z"


def vector(body):
    tx = 54 - CENTER[0] * SCALE
    ty = 54 - CENTER[1] * SCALE
    return (HEADER +
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="108dp" android:height="108dp"\n'
            '    android:viewportWidth="108" android:viewportHeight="108">\n'
            f'    <group android:translateX="{tx:.3f}" android:translateY="{ty:.3f}" '
            f'android:scaleX="{SCALE}" android:scaleY="{SCALE}">\n{body}    </group>\n</vector>\n')


# Signal geometry in head units, shared with make_store_assets.py: bar (x, y, w, h), lamps (cx, cy, r).
# Green is the top lamp of a two-aspect head; the bottom one is dark.
BAR = (5, 0.55, 8, 16)
LIT = (9, 4.6, 2.25)
OFF = (9, 12.5, 2.25)
GLOW_RADIUS = 3.05
HATCH_PITCH = 1.0  # spacing of the diagonal stripes shading the dark lamp in the themed icon

HEAD_BAR = rounded_bar(*BAR)
LIT_LAMP = circle(*LIT)
OFF_LAMP = circle(*OFF)

FOREGROUND = vector(
    f'        <path android:fillColor="{DARK}" android:pathData="{HEAD_BAR}"/>\n'
    f'        <path android:fillColor="{UNLIT}" android:pathData="{OFF_LAMP}"/>\n'
    f'        <path android:fillColor="{GLOW}" android:pathData="{circle(LIT[0], LIT[1], GLOW_RADIUS)}"/>\n'
    f'        <path android:fillColor="{GREEN}" android:pathData="{LIT_LAMP}"/>\n'
)



def hatch(cx, cy, r, pitch):
    """Diagonal stripes (rising to the right) filling the circle, as one path of chord-bounded bands."""
    bands = []
    # Stripe k covers u in [k*pitch, k*pitch + pitch/2], where u is the offset along the (1, 1) normal.
    k = -int(r / pitch) - 1
    while k * pitch < r:
        u0, u1 = max(k * pitch, -r), min(k * pitch + pitch / 2, r)
        if u1 > u0:
            pts = []
            for u, sign in ((u0, 1), (u1, -1)):
                half = (r * r - u * u) ** 0.5
                # Points on the circle at offset u along the normal, v = +/- half along the stripe.
                for v in (-half, half)[::sign]:
                    pts.append((cx + (u - v) / 2 ** 0.5, cy + (u + v) / 2 ** 0.5))
            a, b, c, d = pts
            bands.append(f"M{n(a[0])},{n(a[1])} L{n(b[0])},{n(b[1])} A{n(r)},{n(r)} 0 0 0 {n(c[0])},{n(c[1])} "
                         f"L{n(d[0])},{n(d[1])} A{n(r)},{n(r)} 0 0 0 {n(a[0])},{n(a[1])} Z")
        k += 1
    return " ".join(bands)


# Themed icons are single-colour silhouettes: the signal head with its lamps cut out, the dark one
# clear and the lit one shaded with diagonal stripes, which stand in for its colour.
MONOCHROME = vector(
    f'        <path android:fillColor="{DARK}" android:fillType="evenOdd" '
    f'android:pathData="{HEAD_BAR} {LIT_LAMP} {OFF_LAMP}"/>\n'
    f'        <path android:fillColor="{DARK}" android:pathData="{hatch(*LIT, HATCH_PITCH)}"/>\n'
)

BACKGROUND = (HEADER +
              '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
              '    android:width="108dp" android:height="108dp"\n'
              '    android:viewportWidth="108" android:viewportHeight="108">\n'
              f'    <path android:fillColor="{ORANGE}" android:pathData="M0,0h108v108H0z"/>\n</vector>\n')

ADAPTIVE = (HEADER +
            '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@drawable/ic_launcher_background" />\n'
            '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
            '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
            '</adaptive-icon>\n')


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: make_app_icon.py <android res dir>")
    res = sys.argv[1]
    files = {
        "drawable/ic_launcher_foreground.xml": FOREGROUND,
        "drawable/ic_launcher_background.xml": BACKGROUND,
        "drawable/ic_launcher_monochrome.xml": MONOCHROME,
        "mipmap-anydpi-v26/ic_launcher.xml": ADAPTIVE,
    }
    for path, content in files.items():
        full = os.path.join(res, path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as f:
            f.write(content)
    print(f"wrote {len(files)} icon resources to {res}")


if __name__ == "__main__":
    main()
