#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Joel Haasnoot
"""Write the Android launcher icon: a two-lamp signal head showing green on the app's orange, as
adaptive-icon vector drawables (foreground, background, monochrome). The head matches the map's
signal icons from make_unknown_signal_icons.py.

Usage: make_app_icon.py <android res dir>
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from make_unknown_signal_icons import HEAD  # noqa: E402

ORANGE = "#FFE8640A"
DARK = "#FF" + HEAD.lstrip("#").upper()
UNLIT = "#FF5A5A5A"
GREEN = "#FF2EE06F"
GLOW = "#662EE06F"
SCALE = 3.3  # keeps the signal inside the 66 dp safe zone of the 108 dp adaptive icon
CENTER = (9.0, 8.55)  # centre of the signal head in its 18 x 17.12 units

HEADER = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by pipeline/make_app_icon.py -->\n'


def n(value):
    return f"{value:.3f}".rstrip("0").rstrip(".")


def rounded_bar(x, y, w, h):
    r = w / 2
    return (f"M{n(x + r)},{n(y)} A{n(r)},{n(r)} 0 0 1 {n(x + w)},{n(y + r)} L{n(x + w)},{n(y + h - r)} "
            f"A{n(r)},{n(r)} 0 0 1 {n(x)},{n(y + h - r)} L{n(x)},{n(y + r)} A{n(r)},{n(r)} 0 0 1 {n(x + r)},{n(y)} Z")


def circle(cx, cy, r):
    return f"M{n(cx - r)},{n(cy)} A{n(r)},{n(r)} 0 1 1 {n(cx + r)},{n(cy)} A{n(r)},{n(r)} 0 1 1 {n(cx - r)},{n(cy)} Z"


def vector(body):
    tx = 54 - CENTER[0] * SCALE
    ty = 54 - CENTER[1] * SCALE
    return (HEADER +
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="108dp" android:height="108dp"\n'
            '    android:viewportWidth="108" android:viewportHeight="108">\n'
            f'    <group android:translateX="{tx:.3f}" android:translateY="{ty:.3f}" '
            f'android:scaleX="{SCALE}" android:scaleY="{SCALE}">\n{body}    </group>\n</vector>\n')


HEAD_BAR = rounded_bar(5, 0.55, 8, 16)
TOP_LAMP = circle(9, 4.6, 2.25)
BOTTOM_LAMP = circle(9, 12.5, 2.25)

FOREGROUND = vector(
    f'        <path android:fillColor="{DARK}" android:pathData="{HEAD_BAR}"/>\n'
    f'        <path android:fillColor="{UNLIT}" android:pathData="{TOP_LAMP}"/>\n'
    f'        <path android:fillColor="{GLOW}" android:pathData="{circle(9, 12.5, 3.05)}"/>\n'
    f'        <path android:fillColor="{GREEN}" android:pathData="{BOTTOM_LAMP}"/>\n'
)

# Themed icons are single-colour silhouettes: the signal head with its lamps cut out.
MONOCHROME = vector(
    f'        <path android:fillColor="{DARK}" android:fillType="evenOdd" '
    f'android:pathData="{HEAD_BAR} {TOP_LAMP} {BOTTOM_LAMP}"/>\n'
)

BACKGROUND = (HEADER +
              '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
              '    android:width="108dp" android:height="108dp"\n'
              '    android:viewportWidth="108" android:viewportHeight="108">\n'
              f'    <path android:fillColor="{ORANGE}" android:pathData="M0,0h108v108H0z"/>\n</vector>\n')

ADAPTIVE = (HEADER +
            '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@drawable/ic_launcher_background" />\n'
            '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
            '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
            '</adaptive-icon>\n')


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: make_app_icon.py <android res dir>")
    res = sys.argv[1]
    files = {
        "drawable/ic_launcher_foreground.xml": FOREGROUND,
        "drawable/ic_launcher_background.xml": BACKGROUND,
        "drawable/ic_launcher_monochrome.xml": MONOCHROME,
        "mipmap-anydpi-v26/ic_launcher.xml": ADAPTIVE,
    }
    for path, content in files.items():
        full = os.path.join(res, path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as f:
            f.write(content)
    print(f"wrote {len(files)} icon resources to {res}")


if __name__ == "__main__":
    main()
