#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Joel Haasnoot
"""Turn the generated OpenRailwayMap style + sprites + fonts into Android app assets.

Reads (from the pipeline work dir):
  work/style.json                        generated with `node proxy/js/styles.mjs`
  work/sprites/{sprite,sdf_sprite}_*     generated by Martin from the symbols/ directory
  work/OpenRailwayMap-vector/proxy/font  glyph PBFs

Writes (to android/app/src/main/assets):
  style/orm-style.json   sources point at the {{ORM_TILES}} placeholder, sprite/glyphs to asset://
  sprites/symbols*.json|png   default + SDF sprite sheets merged (SDF icons prefixed with "sdf:")
  font/...
"""
import json
import os
import re
import shutil
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORK = os.path.join(ROOT, "pipeline", "work")
ASSETS = os.path.join(ROOT, "android", "app", "src", "main", "assets")

DROP_SOURCES = {"openhistoricalmap", "dem"}
ATTRIBUTION = '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a> · <a href="https://openrailwaymap.app">OpenRailwayMap</a>'


# --- MapLibre Native compatibility -------------------------------------------------------------
# The upstream style targets MapLibre GL JS. MapLibre Native lacks a few features; patch them here.

DATA_OPS = {"get", "has", "feature-state", "properties", "id", "geometry-type"}


def is_data_driven(e):
    if isinstance(e, list):
        if e and isinstance(e[0], str) and e[0] in DATA_OPS:
            return True
        return any(is_data_driven(x) for x in e)
    return False


HSL_SPACE = re.compile(r"hsla?\(\s*([-\d.]+)(deg)?\s+([-\d.]+%)\s+([-\d.]+%)\s*(?:/\s*([-\d.]+%?))?\s*\)")


def fix_colors(e):
    """MapLibre Native only understands comma-separated hsl(); rewrite CSS Color 4 space syntax."""
    if isinstance(e, str):
        def repl(m):
            h, _, s, l, a = m.groups()
            if a is None:
                return f"hsl({h}, {s}, {l})"
            return f"hsla({h}, {s}, {l}, {a})"
        return HSL_SPACE.sub(repl, e)
    if isinstance(e, list):
        return [fix_colors(x) for x in e]
    if isinstance(e, dict):
        return {k: fix_colors(v) for k, v in e.items()}
    return e


def replace_op(e, old, new):
    """Recursively rename expression operator `old` to `new`."""
    if isinstance(e, list):
        out = [replace_op(x, old, new) for x in e]
        if out and out[0] == old:
            out[0] = new
        return out
    if isinstance(e, dict):
        return {k: replace_op(v, old, new) for k, v in e.items()}
    return e


def and_filter(existing, extra):
    if existing is None:
        return extra
    return ["all", existing, extra]


def split_data_driven(layer, prop):
    """Native cannot evaluate per-feature values for `prop` (e.g. line-dasharray, text-font).

    Split the layer into one layer per branch of a `match`/single-condition `case` expression,
    adding the branch condition to the layer filter. Returns a list of layers.
    """
    section = "paint" if prop in layer.get("paint", {}) else "layout"
    expr = layer[section][prop]
    if not is_data_driven(expr):
        return [layer]
    base_filter = layer.get("filter")

    def clone(suffix, value, extra_filter):
        copy = json.loads(json.dumps(layer))
        copy["id"] = f"{layer['id']}__{suffix}"
        copy[section][prop] = value
        copy["filter"] = and_filter(base_filter, extra_filter)
        return copy

    if expr[0] == "match" and isinstance(expr[1], list) and expr[1][0] == "get" and not is_data_driven(expr[2:]):
        key = expr[1][1]
        branches = expr[2:-1]
        fallback = expr[-1]
        result = []
        all_labels = []
        for i in range(0, len(branches), 2):
            labels = branches[i] if isinstance(branches[i], list) else [branches[i]]
            all_labels.extend(labels)
            result.append(clone(f"m{i // 2}", branches[i + 1], ["in", ["get", key], ["literal", labels]]))
        result.append(clone("mf", fallback, ["!", ["in", ["get", key], ["literal", all_labels]]]))
        return result
    if expr[0] == "case" and len(expr) == 4 and not is_data_driven(expr[2:]):
        return [clone("c1", expr[2], expr[1]), clone("c0", expr[3], ["!", expr[1]])]
    print(f"WARNING: cannot split {prop} of layer {layer['id']}, using fallback value: {json.dumps(expr)[:120]}")
    layer[section][prop] = expr[-1]
    return [layer]


def patch_for_native(style):
    style["layers"] = fix_colors(replace_op(style["layers"], "interpolate-hcl", "interpolate"))
    layers = []
    for layer in style["layers"]:
        layout = layer.get("layout", {})
        if "icon-overlap" in layout:
            layout["icon-allow-overlap"] = layout.pop("icon-overlap") == "always"
        if "text-overlap" in layout:
            layout["text-allow-overlap"] = layout.pop("text-overlap") == "always"
        expanded = [layer]
        for prop in ("line-dasharray", "text-font"):
            expanded = [x for l in expanded for x in split_data_driven(l, prop)] if any(
                prop in l.get("paint", {}) or prop in l.get("layout", {}) for l in expanded) else expanded
        layers.extend(expanded)
    print(f"native patch: {len(style['layers'])} -> {len(layers)} layers")
    style["layers"] = layers


def prepare_style():
    style = json.load(open(os.path.join(WORK, "style.json"), encoding="utf-8"))
    before = len(style["layers"])
    style["layers"] = [l for l in style["layers"] if l.get("source") not in DROP_SOURCES]
    for s in DROP_SOURCES:
        style["sources"].pop(s, None)
    for name, src in style["sources"].items():
        if src.get("type") == "vector":
            src["url"] = "{{ORM_TILES}}"
            src.pop("metadata", None)
            src["attribution"] = ATTRIBUTION
    patch_for_native(style)
    style["sprite"] = "asset://sprites/symbols"
    style["glyphs"] = "asset://font/{fontstack}/{range}.pbf"
    style["name"] = "OpenRailwayMap (offline)"
    # `bearing` defaults to null upstream; it only matters for pitched views, and null breaks
    # numeric expression parsing once substituted, so use 0.
    style.setdefault("state", {}).setdefault("bearing", {})["default"] = 0
    os.makedirs(os.path.join(ASSETS, "style"), exist_ok=True)
    with open(os.path.join(ASSETS, "style", "orm-style.json"), "w", encoding="utf-8") as f:
        json.dump(style, f, separators=(",", ":"), ensure_ascii=False)
    print(f"style: {before} -> {len(style['layers'])} layers, {len(style['sources'])} sources")


def merge_sprites(suffix):
    sdir = os.path.join(WORK, "sprites")
    default_json = json.load(open(os.path.join(sdir, f"sprite_symbols{suffix}.json")))
    sdf_json = json.load(open(os.path.join(sdir, f"sdf_sprite_symbols{suffix}.json")))
    default_png = Image.open(os.path.join(sdir, f"sprite_symbols{suffix}.png")).convert("RGBA")
    sdf_png = Image.open(os.path.join(sdir, f"sdf_sprite_symbols{suffix}.png")).convert("RGBA")

    merged = Image.new("RGBA", (max(default_png.width, sdf_png.width), default_png.height + sdf_png.height))
    merged.paste(default_png, (0, 0))
    merged.paste(sdf_png, (0, default_png.height))

    index = dict(default_json)
    for name, entry in sdf_json.items():
        e = dict(entry)
        e["y"] = e["y"] + default_png.height
        e["sdf"] = True
        index[f"sdf:{name}"] = e

    out = os.path.join(ASSETS, "sprites")
    os.makedirs(out, exist_ok=True)
    merged.save(os.path.join(out, f"symbols{suffix}.png"), optimize=True)
    with open(os.path.join(out, f"symbols{suffix}.json"), "w") as f:
        json.dump(index, f, separators=(",", ":"))
    print(f"sprites{suffix}: {len(index)} icons, {merged.width}x{merged.height}")


def prepare_legend():
    """Copy the upstream legend (what each colour/symbol means), minus sources the app does not have."""
    legend = json.load(open(os.path.join(WORK, "legend.json"), encoding="utf-8"))
    legend.pop("route", None)  # the app has no route view

    def add_localized_name(props):
        # The tile server adds localized_name (the name in the requested language) to stations;
        # the legend samples only carry name, which would leave station samples without text.
        if props and "name" in props and "localized_name" not in props:
            props["localized_name"] = props["name"]

    for style in legend.values():
        style["sourceLayers"] = {
            name: data for name, data in style["sourceLayers"].items()
            if name.split("-", 1)[0] not in DROP_SOURCES
        }
        for data in style["sourceLayers"].values():
            for item in data.get("features", []):
                add_localized_name(item.get("properties"))
                for variant in item.get("variants", []):
                    add_localized_name(variant.get("properties"))
    os.makedirs(os.path.join(ASSETS, "style"), exist_ok=True)
    with open(os.path.join(ASSETS, "style", "legend.json"), "w", encoding="utf-8") as f:
        json.dump(legend, f, separators=(",", ":"), ensure_ascii=False)
    entries = sum(len(d.get("features", [])) for st in legend.values() for d in st["sourceLayers"].values())
    print(f"legend: {len(legend)} views, {entries} entries")


def copy_fonts():
    src = os.path.join(WORK, "OpenRailwayMap-vector", "proxy", "font")
    dst = os.path.join(ASSETS, "font")
    if os.path.isdir(dst):
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    print(f"fonts: {sorted(os.listdir(dst))}")


if __name__ == "__main__":
    prepare_style()
    prepare_legend()
    merge_sprites("")
    merge_sprites("@2x")
    copy_fonts()
